/**
 * Generated by `npm run assets` — do not edit.
 *
 * Intrinsic size and available encode widths for every photograph in
 * `public/images`. `ImageSlot` reads this to reserve the right box and to
 * publish a `srcset`.
 */
export type ImageVariant = { width: number; height: number; widths: number[] };

export const imageVariants: Record<string, ImageVariant> = {
  "/images/academy-world.webp": {
    "width": 1400,
    "height": 1875,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  },
  "/images/auto-gallery.webp": {
    "width": 1400,
    "height": 1875,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  },
  "/images/call-gallery.webp": {
    "width": 1400,
    "height": 1875,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  },
  "/images/chat-gallery.webp": {
    "width": 1400,
    "height": 1875,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  },
  "/images/course-ai-banner.webp": {
    "width": 1600,
    "height": 914,
    "widths": [
      480,
      768,
      1200,
      1600
    ]
  },
  "/images/course-ai-building.webp": {
    "width": 1080,
    "height": 1890,
    "widths": [
      480,
      768,
      1080
    ]
  },
  "/images/course-ai-hero.webp": {
    "width": 1200,
    "height": 1200,
    "widths": [
      480,
      768,
      1200
    ]
  },
  "/images/course-ai-journey.webp": {
    "width": 1080,
    "height": 1389,
    "widths": [
      480,
      768,
      1080
    ]
  },
  "/images/course-ai-session.webp": {
    "width": 1200,
    "height": 1200,
    "widths": [
      480,
      768,
      1200
    ]
  },
  "/images/course-ai-story.webp": {
    "width": 1080,
    "height": 1890,
    "widths": [
      480,
      768,
      1080
    ]
  },
  "/images/course-ai-wide.webp": {
    "width": 2000,
    "height": 848,
    "widths": [
      480,
      768,
      1200,
      2000
    ]
  },
  "/images/course-mentor.webp": {
    "width": 1400,
    "height": 1875,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  },
  "/images/ex-academy.webp": {
    "width": 1400,
    "height": 781,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  },
  "/images/ex-admissions.webp": {
    "width": 1400,
    "height": 781,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  },
  "/images/ex-auto.webp": {
    "width": 1400,
    "height": 781,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  },
  "/images/ex-clean.webp": {
    "width": 1400,
    "height": 781,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  },
  "/images/ex-finance.webp": {
    "width": 1400,
    "height": 781,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  },
  "/images/ex-gym.webp": {
    "width": 1400,
    "height": 781,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  },
  "/images/ex-realty.webp": {
    "width": 1400,
    "height": 781,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  },
  "/images/ex-school.webp": {
    "width": 1400,
    "height": 781,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  },
  "/images/ex-spa.webp": {
    "width": 1400,
    "height": 781,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  },
  "/images/examples-collage.webp": {
    "width": 1400,
    "height": 1875,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  },
  "/images/home-academy.webp": {
    "width": 1400,
    "height": 1875,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  },
  "/images/web-gallery.webp": {
    "width": 1400,
    "height": 1875,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  },
  "/images/web-hero.webp": {
    "width": 1400,
    "height": 1003,
    "widths": [
      480,
      768,
      1200,
      1400
    ]
  }
};
