import { ORDER_STATUSES, PAYMENT_STATUSES } from '../order-status';
import type { KeyedTable } from '../supabase/types';

/**
 * Every table an admin can edit, described once.
 *
 * One registry drives the list view, the create form, the edit form and the
 * server action's type coercion, so "add a column" is a single edit here rather
 * than four screens that can disagree. It is also what makes the dashboard
 * fully open-ended: anything described here is creatable and editable by hand,
 * including free-form orders and invoices with arbitrary items and prices.
 *
 * `key` is the Postgres column name, so every form field posts back under the
 * name the database already uses and nothing has to be translated on the way in.
 */

export type FieldType =
  | 'text'
  | 'textarea'
  | 'number'
  | 'checkbox'
  | 'select'
  | 'list'
  | 'datetime'
  | 'email'
  /** A key into another table. Blank clears it; Postgres rejects ''. */
  | 'uuid'
  | 'json';

export type ResourceField = {
  key: string;
  label: string;
  type: FieldType;
  hint?: string;
  rows?: number;
  options?: readonly string[];
  /** Renders across both form columns. */
  wide?: boolean;
};

export type Resource = {
  /** URL segment under /dashboard/manage. */
  id: string;
  label: string;
  singular: string;
  icon: string;
  tint: string;
  table: KeyedTable;
  group: 'Work' | 'Money' | 'People' | 'Content' | 'System';
  fields: ResourceField[];
  /** Column shown as the row's headline. */
  primary: string;
  /** Columns joined into the row's meta line. */
  meta?: string[];
  /** Column rendered as the status badge. */
  badge?: string;
  /** Default sort. `created_at` desc unless a column is named. */
  sort?: { key: string; dir: 'asc' | 'desc' };
  /** Columns a free-text search runs against, server-side. */
  searchable?: string[];
  /** Blocked when the rows are produced by the app rather than by hand. */
  creatable?: boolean;
  deletable?: boolean;
  /** Shown under the heading to explain what the table is for. */
  note?: string;
};

const published: ResourceField = { key: 'published', label: 'Published', type: 'checkbox' };
const sortOrder: ResourceField = { key: 'sort_order', label: 'Sort order', type: 'number' };

export const resources: Resource[] = [
  /* ── Work ───────────────────────────────────────────────────────── */
  {
    id: 'orders',
    label: 'Orders',
    singular: 'order',
    icon: '🧾',
    tint: '#FFEDE3',
    table: 'orders',
    group: 'Work',
    primary: 'ref',
    meta: ['name', 'email', 'item_name', 'plan_name'],
    badge: 'status',
    searchable: ['ref', 'name', 'email', 'item_name'],
    creatable: true,
    deletable: true,
    note: 'Raise an order by hand for anything at all — the item, plan, price and currency are free text.',
    fields: [
      { key: 'ref', label: 'Reference', type: 'text', hint: 'Left blank on create, we allocate the next one' },
      { key: 'status', label: 'Status', type: 'select', options: ORDER_STATUSES },
      { key: 'payment_status', label: 'Payment', type: 'select', options: PAYMENT_STATUSES },
      { key: 'verified', label: 'Verified (unlocks product access)', type: 'checkbox' },
      { key: 'name', label: 'Customer name', type: 'text' },
      { key: 'email', label: 'Customer email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'company', label: 'Company', type: 'text' },
      { key: 'country', label: 'Country', type: 'text' },
      { key: 'user_id', label: 'Account id', type: 'uuid', hint: 'Links the order to a signed-in account' },
      { key: 'item_id', label: 'Item id', type: 'text', hint: 'Any value — use "custom" for a bespoke job' },
      { key: 'item_name', label: 'Item name', type: 'text' },
      { key: 'plan_id', label: 'Plan id', type: 'text' },
      { key: 'plan_name', label: 'Plan name', type: 'text' },
      { key: 'group_key', label: 'Group', type: 'text' },
      { key: 'price', label: 'List price', type: 'number' },
      { key: 'unit', label: 'Unit', type: 'text', hint: 'e.g. /month, one-time' },
      { key: 'currency', label: 'Currency', type: 'text', hint: 'USD, PKR, USDT, BTC' },
      { key: 'amount_due', label: 'Amount due', type: 'number', hint: 'What the customer is actually asked to pay' },
      { key: 'amount_paid', label: 'Amount paid', type: 'number' },
      { key: 'custom', label: 'Custom order', type: 'checkbox' },
      {
        key: 'custom_items',
        label: 'Custom line items',
        type: 'json',
        wide: true,
        rows: 5,
        hint: 'JSON array, e.g. [{"description":"Extra landing page","qty":2,"unitPrice":150}]',
      },
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'normal', 'high'] },
      { key: 'assigned_to', label: 'Assigned to', type: 'text' },
      { key: 'due_at', label: 'Due', type: 'datetime' },
      { key: 'paid_at', label: 'Paid at', type: 'datetime' },
      { key: 'notes', label: 'Customer notes', type: 'textarea', wide: true, rows: 3 },
      { key: 'admin_notes', label: 'Internal notes', type: 'textarea', wide: true, rows: 3 },
    ],
  },
  {
    id: 'leads',
    label: 'Leads',
    singular: 'lead',
    icon: '🎯',
    tint: '#EEEBFE',
    table: 'leads',
    group: 'Work',
    primary: 'name',
    meta: ['email', 'phone', 'company', 'source'],
    badge: 'status',
    searchable: ['name', 'email', 'company'],
    creatable: true,
    deletable: true,
    note: 'A lead needs an email or a phone number — Postgres refuses one with neither.',
    fields: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'company', label: 'Company', type: 'text' },
      { key: 'website', label: 'Website', type: 'text' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['new', 'contacted', 'qualified', 'won', 'lost', 'spam'],
      },
      { key: 'source', label: 'Source', type: 'select', options: ['website', 'chatbot', 'referral', 'manual'] },
      { key: 'service_slug', label: 'Service', type: 'text' },
      { key: 'package_slug', label: 'Package', type: 'text' },
      { key: 'budget', label: 'Budget', type: 'text' },
      { key: 'country', label: 'Country', type: 'text' },
      { key: 'message', label: 'Message', type: 'textarea', wide: true, rows: 4 },
      { key: 'notes', label: 'Internal notes', type: 'textarea', wide: true, rows: 3 },
    ],
  },
  {
    id: 'bookings',
    label: 'Bookings',
    singular: 'booking',
    icon: '📅',
    tint: '#E9FBF3',
    table: 'bookings',
    group: 'Work',
    primary: 'name',
    meta: ['email', 'slot_at', 'channel'],
    badge: 'status',
    sort: { key: 'slot_at', dir: 'desc' },
    searchable: ['name', 'email'],
    creatable: true,
    deletable: true,
    fields: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'company', label: 'Company', type: 'text' },
      { key: 'service_slug', label: 'Service', type: 'text' },
      { key: 'slot_at', label: 'Slot', type: 'datetime' },
      { key: 'timezone', label: 'Timezone', type: 'text' },
      { key: 'channel', label: 'Channel', type: 'select', options: ['call', 'whatsapp', 'meet'] },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['requested', 'confirmed', 'completed', 'cancelled', 'no_show'],
      },
      { key: 'notes', label: 'Notes', type: 'textarea', wide: true, rows: 3 },
    ],
  },
  {
    id: 'inbox',
    label: 'Contact inbox',
    singular: 'message',
    icon: '✉️',
    tint: '#FFF0E7',
    table: 'contact_messages',
    group: 'Work',
    primary: 'name',
    meta: ['email', 'subject'],
    badge: 'status',
    searchable: ['name', 'email', 'subject'],
    deletable: true,
    fields: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'subject', label: 'Subject', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['unread', 'read', 'replied', 'spam'] },
      { key: 'message', label: 'Message', type: 'textarea', wide: true, rows: 6 },
    ],
  },
  {
    id: 'threads',
    label: 'Support threads',
    singular: 'thread',
    icon: '💬',
    tint: '#E9FBF3',
    table: 'threads',
    group: 'Work',
    primary: 'subject',
    meta: ['name', 'email', 'order_ref'],
    badge: 'status',
    sort: { key: 'last_message_at', dir: 'desc' },
    searchable: ['subject', 'name', 'email'],
    creatable: true,
    deletable: true,
    fields: [
      { key: 'subject', label: 'Subject', type: 'text', wide: true },
      { key: 'user_id', label: 'Account id', type: 'uuid' },
      { key: 'name', label: 'Customer name', type: 'text' },
      { key: 'email', label: 'Customer email', type: 'email' },
      { key: 'order_ref', label: 'Order reference', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'pending', 'resolved', 'closed'] },
      { key: 'unread_for_staff', label: 'Needs our reply', type: 'checkbox' },
      { key: 'unread_for_customer', label: 'Waiting on the customer', type: 'checkbox' },
    ],
  },
  {
    id: 'chats',
    label: 'Pip conversations',
    singular: 'conversation',
    icon: '🐦',
    tint: '#FFF0E7',
    table: 'chat_conversations',
    group: 'Work',
    primary: 'name',
    meta: ['email', 'user_id', 'message_count'],
    badge: 'status',
    sort: { key: 'last_message_at', dir: 'desc' },
    searchable: ['name', 'email'],
    creatable: false,
    deletable: true,
    note: 'Transcripts from the Pip assistant. Read and tidy here; the assistant writes them itself.',
    fields: [
      { key: 'user_id', label: 'Account id', type: 'uuid' },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'handoff', 'closed'] },
      { key: 'summary', label: 'Summary', type: 'textarea', wide: true, rows: 4 },
    ],
  },

  /* ── Money ──────────────────────────────────────────────────────── */
  {
    id: 'invoices',
    label: 'Invoices',
    singular: 'invoice',
    icon: '💳',
    tint: '#FFF4D8',
    table: 'invoices',
    group: 'Money',
    primary: 'number',
    meta: ['name', 'email', 'title'],
    badge: 'status',
    searchable: ['number', 'name', 'email', 'title'],
    creatable: true,
    deletable: true,
    note: 'Bill anything. Line items are free-form, and the totals are whatever you type.',
    fields: [
      { key: 'number', label: 'Number', type: 'text', hint: 'Left blank on create, we allocate the next one' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'name', label: 'Customer name', type: 'text' },
      { key: 'email', label: 'Customer email', type: 'email' },
      { key: 'company', label: 'Company', type: 'text' },
      { key: 'user_id', label: 'Account id', type: 'uuid' },
      { key: 'order_ref', label: 'Order reference', type: 'text' },
      { key: 'order_id', label: 'Order id', type: 'uuid' },
      { key: 'currency', label: 'Currency', type: 'text' },
      {
        key: 'line_items',
        label: 'Line items',
        type: 'json',
        wide: true,
        rows: 6,
        hint: 'JSON array, e.g. [{"description":"Business build","qty":1,"unitPrice":1200}]',
      },
      { key: 'subtotal', label: 'Subtotal', type: 'number' },
      { key: 'discount', label: 'Discount', type: 'number' },
      { key: 'tax', label: 'Tax', type: 'number' },
      { key: 'total', label: 'Total', type: 'number', hint: 'Leave 0 to compute from the line items' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'sent', 'paid', 'overdue', 'void'] },
      { key: 'issued_at', label: 'Issued', type: 'datetime' },
      { key: 'due_at', label: 'Due', type: 'datetime' },
      { key: 'paid_at', label: 'Paid', type: 'datetime' },
      { key: 'notes', label: 'Notes', type: 'textarea', wide: true, rows: 3 },
    ],
  },
  {
    id: 'payments',
    label: 'Payments',
    singular: 'payment',
    icon: '🪙',
    tint: '#E9FBF3',
    table: 'payments',
    group: 'Money',
    primary: 'ref',
    meta: ['name', 'order_ref', 'method_label', 'reference'],
    badge: 'status',
    searchable: ['ref', 'name', 'order_ref', 'reference'],
    creatable: true,
    deletable: true,
    note: 'Every transfer a customer says they made, with the screenshot they uploaded.',
    fields: [
      { key: 'ref', label: 'Reference', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['submitted', 'verified', 'rejected', 'refunded'] },
      { key: 'order_ref', label: 'Order reference', type: 'text' },
      { key: 'order_id', label: 'Order id', type: 'uuid' },
      { key: 'invoice_number', label: 'Invoice number', type: 'text' },
      { key: 'name', label: 'Payer name', type: 'text' },
      { key: 'email', label: 'Payer email', type: 'email' },
      { key: 'user_id', label: 'Account id', type: 'uuid' },
      { key: 'method', label: 'Method id', type: 'text' },
      { key: 'method_label', label: 'Method label', type: 'text' },
      { key: 'currency', label: 'Currency', type: 'text' },
      { key: 'amount', label: 'Amount sent', type: 'number' },
      { key: 'amount_usd', label: 'Amount in USD', type: 'number' },
      { key: 'reference', label: 'Transaction id', type: 'text' },
      { key: 'proof_path', label: 'Proof object path', type: 'text' },
      { key: 'note', label: 'Customer note', type: 'textarea', wide: true, rows: 3 },
      { key: 'admin_note', label: 'Internal note', type: 'textarea', wide: true, rows: 3 },
    ],
  },
  {
    id: 'methods',
    label: 'Payment details',
    singular: 'payment method',
    icon: '🏦',
    tint: '#FFF4D8',
    table: 'payment_methods',
    group: 'Money',
    primary: 'label',
    meta: ['currency', 'network', 'address'],
    sort: { key: 'sort_order', dir: 'asc' },
    searchable: ['label', 'currency', 'method_id'],
    creatable: true,
    deletable: true,
    note: 'The addresses and accounts customers are asked to pay into. Shown on the payment screen exactly as written here.',
    fields: [
      { key: 'method_id', label: 'Method id', type: 'text', hint: 'Stable key, e.g. usdt-trc20' },
      { key: 'label', label: 'Label', type: 'text' },
      { key: 'kind', label: 'Kind', type: 'select', options: ['crypto', 'bank'] },
      { key: 'currency', label: 'Currency', type: 'text' },
      { key: 'address', label: 'Address or account number', type: 'text', wide: true },
      { key: 'network', label: 'Network', type: 'text', hint: 'TRC20, Bitcoin — blank for a bank' },
      { key: 'account_name', label: 'Account name', type: 'text' },
      { key: 'bank_name', label: 'Bank name', type: 'text' },
      { key: 'branch', label: 'Branch', type: 'text' },
      { key: 'iban', label: 'IBAN', type: 'text' },
      { key: 'swift', label: 'SWIFT / BIC', type: 'text' },
      { key: 'icon', label: 'Icon', type: 'text', hint: 'A single emoji' },
      { key: 'tint', label: 'Tint', type: 'text' },
      { key: 'instructions', label: 'Instructions', type: 'textarea', wide: true, rows: 3 },
      { key: 'enabled', label: 'Shown to customers', type: 'checkbox' },
      sortOrder,
    ],
  },

  /* ── People ─────────────────────────────────────────────────────── */
  {
    id: 'customers',
    label: 'Customers',
    singular: 'customer',
    icon: '👤',
    tint: '#EEEBFE',
    table: 'profiles',
    group: 'People',
    primary: 'name',
    meta: ['email', 'phone', 'company', 'country'],
    searchable: ['name', 'email', 'company'],
    // A profile is one-to-one with an account, and the database creates it when
    // the account is created. There is nothing to make by hand.
    creatable: false,
    deletable: false,
    note: 'One row per account, created automatically at sign-up. Deleting the account removes it.',
    fields: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'company', label: 'Company', type: 'text' },
      { key: 'country', label: 'Country', type: 'text' },
      { key: 'city', label: 'City', type: 'text' },
      { key: 'address', label: 'Address', type: 'text', wide: true },
      { key: 'timezone', label: 'Timezone', type: 'text' },
      { key: 'referral_code', label: 'Referral code', type: 'text' },
      { key: 'notify_orders', label: 'Order emails', type: 'checkbox' },
      { key: 'notify_invoices', label: 'Invoice emails', type: 'checkbox' },
      { key: 'notify_classes', label: 'Class emails', type: 'checkbox' },
      { key: 'notify_news', label: 'Product news', type: 'checkbox' },
      { key: 'notes', label: 'Internal notes', type: 'textarea', wide: true, rows: 3 },
    ],
  },
  {
    id: 'subscribers',
    label: 'Subscribers',
    singular: 'subscriber',
    icon: '📮',
    tint: '#FFF0E7',
    table: 'subscribers',
    group: 'People',
    primary: 'email',
    meta: ['name', 'source'],
    searchable: ['email', 'name'],
    creatable: true,
    deletable: true,
    fields: [
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'source', label: 'Source', type: 'text' },
      { key: 'confirmed', label: 'Confirmed', type: 'checkbox' },
    ],
  },
  {
    id: 'files',
    label: 'Customer files',
    singular: 'file record',
    icon: '📁',
    tint: '#FFF4D8',
    table: 'customer_files',
    group: 'People',
    primary: 'name',
    meta: ['email', 'category', 'order_ref'],
    searchable: ['name', 'email'],
    creatable: false,
    deletable: true,
    note: 'Upload files from a customer’s own page; this list is for correcting the record afterwards.',
    fields: [
      { key: 'user_id', label: 'Account id', type: 'uuid' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'path', label: 'Object path', type: 'text' },
      { key: 'name', label: 'File name', type: 'text' },
      {
        key: 'category',
        label: 'Category',
        type: 'select',
        options: ['brand', 'scope', 'invoice', 'report', 'handover', 'other'],
      },
      { key: 'uploaded_by', label: 'Uploaded by', type: 'select', options: ['customer', 'staff'] },
      { key: 'order_ref', label: 'Order reference', type: 'text' },
      { key: 'visible', label: 'Visible to the customer', type: 'checkbox' },
      { key: 'note', label: 'Note', type: 'textarea', wide: true, rows: 2 },
    ],
  },
  {
    id: 'enrollments',
    label: 'Enrollments',
    singular: 'enrollment',
    icon: '🎓',
    tint: '#EEEBFE',
    table: 'enrollments',
    group: 'People',
    primary: 'student_name',
    meta: ['class_title', 'email'],
    badge: 'status',
    searchable: ['student_name', 'email', 'class_title'],
    creatable: true,
    deletable: true,
    fields: [
      { key: 'class_id', label: 'Class id', type: 'uuid' },
      { key: 'class_title', label: 'Class title', type: 'text' },
      { key: 'user_id', label: 'Account id', type: 'uuid' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'student_name', label: 'Student name', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'paused', 'completed', 'cancelled'] },
      { key: 'attendance', label: 'Attendance %', type: 'number' },
      { key: 'mock_average', label: 'Mock average %', type: 'number' },
      { key: 'homework', label: 'Homework %', type: 'number' },
      { key: 'order_ref', label: 'Order reference', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea', wide: true, rows: 3 },
    ],
  },

  /* ── Content ────────────────────────────────────────────────────── */
  {
    id: 'catalog',
    label: 'Catalog items',
    singular: 'catalog item',
    icon: '📦',
    tint: '#FFEDE3',
    table: 'catalog_items',
    group: 'Content',
    primary: 'name',
    meta: ['item_id', 'group_key'],
    sort: { key: 'sort_order', dir: 'asc' },
    searchable: ['name', 'item_id'],
    creatable: true,
    deletable: true,
    fields: [
      { key: 'item_id', label: 'Item id', type: 'text', hint: 'Stable key, e.g. calling-agent' },
      { key: 'group_key', label: 'Group', type: 'select', options: ['Products', 'Services', 'Academy'] },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'icon', label: 'Icon', type: 'text', hint: 'A single emoji' },
      { key: 'tint', label: 'Tint', type: 'text' },
      { key: 'tagline', label: 'Tagline', type: 'text' },
      { key: 'href', label: 'Link', type: 'text' },
      { key: 'page', label: 'Own page', type: 'text' },
      { key: 'audience', label: 'Audience', type: 'text' },
      { key: 'accent', label: 'Accent', type: 'text' },
      { key: 'wash', label: 'Wash', type: 'text' },
      { key: 'slot', label: 'Image slot', type: 'text' },
      { key: 'photo', label: 'Image caption', type: 'text' },
      { key: 'detail_slot', label: 'Detail image slot', type: 'text' },
      { key: 'detail_photo', label: 'Detail image caption', type: 'text' },
      { key: 'blurb', label: 'Blurb', type: 'textarea', wide: true, rows: 2 },
      { key: 'body', label: 'Card copy', type: 'textarea', wide: true, rows: 4 },
      { key: 'detail_body', label: 'Detail copy', type: 'textarea', wide: true, rows: 4 },
      { key: 'features', label: 'Features', type: 'list', wide: true, hint: 'One per line: title|body' },
      { key: 'stats', label: 'Stats', type: 'list', wide: true, hint: 'One per line: value|label' },
      sortOrder,
      published,
    ],
  },
  {
    id: 'plans',
    label: 'Catalog plans',
    singular: 'plan',
    icon: '🏷️',
    tint: '#FFEDE3',
    table: 'catalog_plans',
    group: 'Content',
    primary: 'name',
    meta: ['plan_id', 'item_id', 'price', 'unit'],
    sort: { key: 'sort_order', dir: 'asc' },
    searchable: ['name', 'plan_id', 'item_id'],
    creatable: true,
    deletable: true,
    note: 'A plan belongs to a catalog item — the item id has to match one that already exists.',
    fields: [
      { key: 'plan_id', label: 'Plan id', type: 'text' },
      { key: 'item_id', label: 'Item id', type: 'text' },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'price', label: 'Price', type: 'number' },
      { key: 'unit', label: 'Unit', type: 'text' },
      { key: 'note', label: 'Note', type: 'text' },
      sortOrder,
    ],
  },
  {
    id: 'examples',
    label: 'Examples',
    singular: 'example',
    icon: '🖼️',
    tint: '#E9FBF3',
    table: 'examples',
    group: 'Content',
    primary: 'title',
    meta: ['group_key', 'kind', 'sector'],
    sort: { key: 'sort_order', dir: 'asc' },
    searchable: ['title', 'sector', 'kind'],
    creatable: true,
    deletable: true,
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'group_key', label: 'Filter key', type: 'text', hint: 'websites, chatbots, calling, automations…' },
      { key: 'kind', label: 'Kind', type: 'text' },
      { key: 'sector', label: 'Sector', type: 'text' },
      { key: 'tint', label: 'Tint', type: 'text' },
      { key: 'slot', label: 'Image slot', type: 'text' },
      { key: 'photo', label: 'Image caption', type: 'text' },
      { key: 'body', label: 'Body', type: 'textarea', wide: true, rows: 5 },
      { key: 'results', label: 'Headline numbers', type: 'list', wide: true, hint: 'One per line: value|label|#colour' },
      sortOrder,
      published,
    ],
  },
  {
    id: 'reviews',
    label: 'Reviews',
    singular: 'review',
    icon: '⭐',
    tint: '#FFF4D8',
    table: 'reviews',
    group: 'Content',
    primary: 'name',
    meta: ['role'],
    sort: { key: 'sort_order', dir: 'asc' },
    searchable: ['name', 'role'],
    creatable: true,
    deletable: true,
    fields: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'initials', label: 'Initials', type: 'text' },
      { key: 'tint', label: 'Tint', type: 'text' },
      { key: 'quote', label: 'Quote', type: 'textarea', wide: true, rows: 4 },
      sortOrder,
      published,
    ],
  },
  {
    id: 'faqs',
    label: 'FAQs',
    singular: 'FAQ',
    icon: '❓',
    tint: '#EEEBFE',
    table: 'faqs',
    group: 'Content',
    primary: 'question',
    meta: ['category'],
    sort: { key: 'sort_order', dir: 'asc' },
    searchable: ['question', 'category'],
    creatable: true,
    deletable: true,
    fields: [
      { key: 'question', label: 'Question', type: 'text', wide: true },
      { key: 'category', label: 'Category', type: 'text' },
      sortOrder,
      { key: 'answer', label: 'Answer', type: 'textarea', wide: true, rows: 5 },
      published,
    ],
  },
  {
    id: 'classes',
    label: 'Academy classes',
    singular: 'class',
    icon: '📚',
    tint: '#EEEBFE',
    table: 'academy_classes',
    group: 'Content',
    primary: 'title',
    meta: ['subject', 'tutor', 'time_label'],
    badge: 'status',
    sort: { key: 'sort_order', dir: 'asc' },
    searchable: ['title', 'subject', 'tutor'],
    creatable: true,
    deletable: true,
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'subject', label: 'Subject', type: 'text' },
      { key: 'tutor', label: 'Tutor', type: 'text' },
      { key: 'level', label: 'Level', type: 'text' },
      { key: 'icon', label: 'Icon', type: 'text' },
      { key: 'tint', label: 'Tint', type: 'text' },
      { key: 'time_label', label: 'Slot label', type: 'text', hint: 'e.g. Mon 6:00 PM GST' },
      { key: 'starts_at', label: 'Next start', type: 'datetime' },
      { key: 'duration_mins', label: 'Duration (minutes)', type: 'number' },
      { key: 'capacity', label: 'Capacity', type: 'number' },
      { key: 'meeting_url', label: 'Meeting link', type: 'text', wide: true },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['scheduled', 'confirmed', 'rescheduling', 'cancelled', 'completed'],
      },
      { key: 'notes', label: 'Notes', type: 'textarea', wide: true, rows: 3 },
      sortOrder,
      published,
    ],
  },

  /* ── System ─────────────────────────────────────────────────────── */
  {
    id: 'settings',
    label: 'Settings',
    singular: 'setting',
    icon: '⚙️',
    tint: '#F1EFE8',
    table: 'settings',
    group: 'System',
    primary: 'key',
    meta: ['group_key'],
    searchable: ['key', 'group_key'],
    creatable: true,
    deletable: true,
    note: 'Free-form key/value pairs the site reads at render time.',
    fields: [
      { key: 'key', label: 'Key', type: 'text' },
      { key: 'group_key', label: 'Group', type: 'text' },
      { key: 'value', label: 'Value', type: 'textarea', wide: true, rows: 4 },
    ],
  },
];

const byId = new Map(resources.map((resource) => [resource.id, resource]));

export function findResource(id: string): Resource | null {
  return byId.get(id) ?? null;
}
